name: Source DB
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Deploying Images'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VHOST }}
          username: ${{ secrets.VUSERNAME }}
          key: ${{ secrets.VPRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.VPASSPHRASE }}
          script: |
              cd /home/bima/agency_db
              git pull
              docker rm $(docker stop $(docker ps -a -q --filter ancestor=clue/json-server --format="{{.ID}}"))
              docker run -d -p 1337:80 -v /home/bima/agency_db/source.json:/data/db.json clue/json-server
      - name: Asana Tix Doing
        uses: TheDotLabs/github-asana-action@v4.0.2
        with:
          asana-token: '1/1200790668297351:fe9df17b2548e660be1e836b79969382'
          targets_commit_push: '[{"project": "AidHub MEP DEV", "section": "Doing"}, {"project": "AidHub MEP DEV", "section": "QA Test .DEV"}]'