name: Source DB
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Deploying Images'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VHOST }}
          username: ${{ secrets.VUSERNAME }}
          key: ${{ secrets.VPRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
              whoami
