name: Source DB
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Deploying Images'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VHOST }}
          username: ${{ secrets.VUSERNAME }}
          key: ${{ secrets.VPRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.VPASSPHRASE }}
          script: |
              cd ~/agency_db
              git pull
              docker rm $(docker stop $(docker ps -a -q --filter ancestor=clue/json-server --format="{{.ID}}"))
              docker run -d -p 1337:80 -v /home/dotamonster/agency_db/source.json:/data/db.json clue/json-server
